### ISSUE TITLE
how compile 

### ISSUE THREAD

**Issue by mohamadpk** [mainfunx/frpc_android#1]
how you compile frpclib? 
can you share your full source of frpc and go env?
can you share androide ndk and sdk version?
i compile frcp but not work correctlly.
tnx

**Comment by mainfunx** [comment]
just follow this [#url](https://github.com/FrpcCluster/frpc-Android/blob/master/Compile_zh.md)

**Comment by mohamadpk** [comment]
tnx @mainfunx .but i follow this [#url](https://github.com/FrpcCluster/frpc-Android/blob/master/Compile_zh.md) many and many time.but all time same problem.

**Comment by mainfunx** [comment]
I just compiled the new version 0.35.1 with NDK 20.0.5594570, but failed with NDK 22.0.7026061, did not try more, the frp source code has been added [here](https://github.com/mainfunx/frpc_android/tree/master/frp), maybe you can send the wrong screenshot to see @mohamadpk
