### ISSUE TITLE
能否帮忙编译一个最新版的frpc？

### ISSUE THREAD

**Issue by wekingchen** [mainfunx/frpc_android#4]
谢谢😊

**Comment by jambestwick** [comment]
？？？

**Comment by jambestwick** [comment]
https://github.com/ETCPark/frpc_android,新编成功的APK，在realse里

**Comment by jambestwick** [comment]
@wekingchen

**Comment by wekingchen** [comment]
@jambestwick 谢谢，可这个版本号还是releases里的版本还是0.35.1.1呀，frp最新版已经是v0.38.0了的嘛

**Comment by jambestwick** [comment]
@wekingchen ，最近忙，cmake很简单

**Comment by bxs17** [comment]
搞完sdk 已经吐血身亡了   . 简单帮编译下咯  环境难搞 而不是cmake

**Comment by bxs17** [comment]
![image](https://user-images.githubusercontent.com/23467964/151319384-cfe6cc2e-40de-4eb9-a1c7-73f94e0195e7.png)

**Comment by mainfunx** [comment]
更新过了

**Comment by wekingchen** [comment]
谢谢啦
